services:
  postgres:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d/
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
volumes:
  db:
    driver: local